# 🏗️ MCP UI Chat Client Monorepo Configuration
# 
# 📚 ОБРАЗОВАТЕЛЬНАЯ ЗАМЕТКА:
# pnpm workspaces позволяют управлять множественными пакетами в одном репозитории
# Это обеспечивает:
# - 🔗 Shared dependencies (избегаем дублирования node_modules)
# - 🚀 Атомарные commits (изменения во всех пакетах одновременно)
# - 🎯 Единые scripts и конфигурации
# - 📦 Symlinks между локальными пакетами для быстрой разработки

packages:
  # 🎨 Main applications
  - "apps/*"
  
  # 📦 Reusable packages  
  - "packages/*"
  
  # 🧪 Examples and demos
  - "examples/*"

# 🔧 Build optimization
# Игнорируем native dependencies для ускорения установки
ignoredBuiltDependencies:
  - '@swc/core'
  - esbuild

# 🎯 ТЕХНИЧЕСКАЯ ЗАМЕТКА:
# Порядок важен! apps/* должен идти первым, так как он зависит от packages/*
# pnpm автоматически разрешает зависимости между workspace пакетами
