name: 🐛 Bug Report
description: Сообщить о проблеме в MCP UI SDK
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - ivan-meer

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за то, что нашли время сообщить о проблеме! 🙏
        
        Пожалуйста, заполните форму ниже как можно подробнее. Это поможет нам быстрее воспроизвести и исправить проблему.

  - type: checkboxes
    id: checklist
    attributes:
      label: Предварительная проверка
      description: Перед отправкой убедитесь, что выполнены следующие условия
      options:
        - label: Я проверил, что нет дублирующих issue
          required: true
        - label: Я использую последнюю версию MCP UI SDK
          required: true
        - label: Я прочитал документацию
          required: true

  - type: dropdown
    id: package
    attributes:
      label: Затрагиваемый пакет
      description: Какой пакет затронут проблемой?
      options:
        - "@mcp-ui/client"
        - "@mcp-ui/server"
        - "@mcp-ui/shared"
        - "examples/server"
        - "docs"
        - "Не уверен"
      default: 0
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Версия
      description: Какую версию MCP UI SDK вы используете?
      placeholder: "например, 2.0.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Среда выполнения
      description: В какой среде возникает проблема?
      options:
        - "Browser"
        - "Node.js"
        - "React App"
        - "Next.js"
        - "Vite"
        - "Другое"
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Описание проблемы
      description: Подробно опишите проблему
      placeholder: |
        Четкое и краткое описание того, что пошло не так.
        
        Например:
        - Что вы пытались сделать?
        - Что произошло?
        - Что должно было произойти?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Шаги для воспроизведения
      description: Пошаговые инструкции для воспроизведения проблемы
      placeholder: |
        1. Перейти к '...'
        2. Нажать на '...'
        3. Прокрутить до '...'
        4. Увидеть ошибку
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
      description: Описание того, что должно происходить
      placeholder: Четкое и краткое описание ожидаемого результата
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Скриншоты/Видео
      description: Если применимо, добавьте скриншоты или видео для объяснения проблемы
      placeholder: Перетащите сюда изображения или видео

  - type: textarea
    id: code
    attributes:
      label: Пример кода
      description: Минимальный пример кода, воспроизводящий проблему
      render: typescript
      placeholder: |
        // Ваш код здесь
        import { HtmlResource } from '@mcp-ui/client';
        
        // ...

  - type: textarea
    id: logs
    attributes:
      label: Логи ошибок
      description: Вставьте здесь любые соответствующие логи ошибок
      render: shell
      placeholder: |
        Ошибки из консоли браузера или терминала

  - type: input
    id: browser
    attributes:
      label: Браузер (если применимо)
      description: Если проблема связана с браузером, укажите название и версию
      placeholder: "например, Chrome 120, Firefox 121, Safari 17"

  - type: input
    id: os
    attributes:
      label: Операционная система
      description: Какую ОС вы используете?
      placeholder: "например, Windows 11, macOS 14, Ubuntu 22.04"

  - type: input
    id: node
    attributes:
      label: Версия Node.js
      description: Какую версию Node.js вы используете?
      placeholder: "например, 18.17.0"

  - type: textarea
    id: context
    attributes:
      label: Дополнительный контекст
      description: Любая другая информация о проблеме
      placeholder: |
        Добавьте любой другой контекст о проблеме здесь.
        
        Например:
        - Когда проблема началась?
        - Происходит ли это постоянно или периодически?
        - Есть ли обходные пути?

  - type: checkboxes
    id: contribution
    attributes:
      label: Готовность помочь
      description: Готовы ли вы помочь с исправлением?
      options:
        - label: Я готов создать Pull Request для исправления этой проблемы
          required: false
        - label: Мне нужна помощь в понимании кодовой базы для исправления
          required: false