name: ✨ Feature Request
description: Предложить новую функцию для MCP UI SDK
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - ivan-meer

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за предложение улучшения MCP UI SDK! 🚀
        
        Мы ценим ваши идеи и хотим понять, как лучше реализовать предлагаемую функцию.

  - type: checkboxes
    id: checklist
    attributes:
      label: Предварительная проверка
      description: Перед отправкой убедитесь, что выполнены следующие условия
      options:
        - label: Я проверил, что подобной функции еще нет
          required: true
        - label: Я проверил существующие feature request'ы
          required: true
        - label: Я прочитал документацию и roadmap
          required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: Тип функции
      description: Какой тип функции вы предлагаете?
      options:
        - "Новый React компонент"
        - "Новая серверная утилита"
        - "Улучшение существующего API"
        - "Новая UI схема (uri://)"
        - "Инструмент разработки"
        - "Улучшение производительности"
        - "Улучшение доступности"
        - "Улучшение документации"
        - "Другое"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Затрагиваемый пакет
      description: Какой пакет должен быть изменен или расширен?
      options:
        - "@mcp-ui/client"
        - "@mcp-ui/server"
        - "@mcp-ui/shared"
        - "examples/server"
        - "docs"
        - "Новый пакет"
        - "Несколько пакетов"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Приоритет
      description: Как вы оцениваете важность этой функции?
      options:
        - "🔥 Критический - блокирует использование SDK"
        - "🚀 Высокий - значительно улучшит workflow"
        - "📈 Средний - полезное улучшение"
        - "💡 Низкий - nice to have"
      default: 2
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Проблема, которую решает функция
      description: Четко опишите проблему или потребность, которую решает предлагаемая функция
      placeholder: |
        Например:
        "Сейчас я не могу [что-то сделать] потому что [причина].
        Это создает проблему, когда [контекст использования]."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
      description: Опишите, как вы видите реализацию этой функции
      placeholder: |
        Подробно опишите предлагаемое решение:
        
        - Как должна работать функция?
        - Какой API вы предлагаете?
        - Как пользователи будут взаимодействовать с ней?
        - Какие компоненты/модули нужно изменить?
    validations:
      required: true

  - type: textarea
    id: api_design
    attributes:
      label: Дизайн API (если применимо)
      description: Предложите дизайн API для новой функции
      render: typescript
      placeholder: |
        // Пример предлагаемого API
        
        // Для клиентского пакета:
        interface NewFeatureProps {
          // ваши props
        }
        
        export function NewFeature(props: NewFeatureProps) {
          // реализация
        }
        
        // Для серверного пакета:
        export function createNewResource(options: NewResourceOptions) {
          // реализация
        }

  - type: textarea
    id: examples
    attributes:
      label: Примеры использования
      description: Покажите, как будет использоваться предлагаемая функция
      render: typescript
      placeholder: |
        // Пример 1: Базовое использование
        import { NewFeature } from '@mcp-ui/client';
        
        function App() {
          return (
            <NewFeature 
              prop1="value1"
              prop2={value2}
            />
          );
        }
        
        // Пример 2: Продвинутое использование
        // ...

  - type: textarea
    id: alternatives
    attributes:
      label: Рассмотренные альтернативы
      description: Опишите альтернативные решения, которые вы рассматривали
      placeholder: |
        - Альтернатива 1: [описание] - [почему не подходит]
        - Альтернатива 2: [описание] - [почему не подходит]
        - Текущий workaround: [если есть]

  - type: checkboxes
    id: breaking_changes
    attributes:
      label: Breaking Changes
      description: Требует ли предлагаемая функция breaking changes?
      options:
        - label: Эта функция требует breaking changes в существующем API
          required: false
        - label: Эта функция может быть добавлена без breaking changes
          required: false
        - label: Не уверен в влиянии на существующий API
          required: false

  - type: textarea
    id: implementation_notes
    attributes:
      label: Заметки по реализации
      description: Технические детали или соображения по реализации
      placeholder: |
        - Требуемые зависимости
        - Потенциальные проблемы производительности
        - Совместимость с браузерами
        - Влияние на размер bundle
        - Требования к тестированию

  - type: dropdown
    id: complexity
    attributes:
      label: Оценка сложности
      description: Как вы оцениваете сложность реализации?
      options:
        - "🟢 Простая - несколько часов работы"
        - "🟡 Средняя - несколько дней работы"
        - "🟠 Сложная - несколько недель работы"
        - "🔴 Очень сложная - требует архитектурных изменений"
        - "❓ Не могу оценить"
      default: 4
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Случаи использования
      description: Опишите конкретные сценарии, где будет полезна эта функция
      placeholder: |
        1. Случай использования 1:
           - Контекст: [где и когда]
           - Проблема: [что не работает сейчас]
           - Решение: [как новая функция поможет]
           
        2. Случай использования 2:
           - ...

  - type: textarea
    id: resources
    attributes:
      label: Дополнительные ресурсы
      description: Ссылки на примеры, документацию или inspiration
      placeholder: |
        - Похожая реализация в другой библиотеке: [ссылка]
        - Спецификация или RFC: [ссылка]
        - Обсуждение в сообществе: [ссылка]
        - Примеры в других проектах: [ссылка]

  - type: checkboxes
    id: contribution
    attributes:
      label: Готовность помочь
      description: Готовы ли вы помочь с реализацией?
      options:
        - label: Я готов создать Pull Request для этой функции
          required: false
        - label: Мне нужна помощь в понимании кодовой базы
          required: false
        - label: Я могу помочь с тестированием
          required: false
        - label: Я могу помочь с документацией
          required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Дополнительный контекст
      description: Любая другая информация о предлагаемой функции
      placeholder: |
        - Связанные issues или PR
        - Временные рамки, когда функция нужна
        - Влияние на ваш проект
        - Другие соображения